# Generated by Django 4.2.11 on 2025-04-29 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmember',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(default=datetime.date(2025, 4, 29)),
        ),
    ]
